operator-path: REPLACE_ROOT_PATHdeploy/operator.yaml
role-paths:
- REPLACE_ROOT_PATHdeploy/role.yaml
- REPLACE_ROOT_PATHdeploy/cluster_role.yaml
crd-cr-paths:
- REPLACE_ROOT_PATHdeploy/crds
- REPLACE_ROOT_PATHexamples
